// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322094735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BienTheSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("MaSize")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSize");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("MaSanPham", "MaSize", "MaMau")
                        .IsUnique();

                    b.ToTable("BienTheSanPhams", t =>
                        {
                            t.HasCheckConstraint("CK_BienTheSanPham_SoLuongTon", "[SoLuongTon] >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaBienThe");

                    b.HasIndex("MaHoaDon", "MaBienThe")
                        .IsUnique();

                    b.ToTable("ChiTietHoaDons", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietHoaDon_DonGia", "[DonGia] >= 0");

                            t.HasCheckConstraint("CK_ChiTietHoaDon_SoLuong", "[SoLuong] > 0");

                            t.HasCheckConstraint("CK_ChiTietHoaDon_ThanhTien", "[ThanhTien] >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaChiTietHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("SoSao")
                        .HasColumnType("tinyint");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaChiTietHoaDon")
                        .IsUnique();

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSanPham");

                    b.ToTable("DanhGias", t =>
                        {
                            t.HasCheckConstraint("CK_DanhGia_SoSao", "[SoSao] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("backend.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenDanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("backend.Models.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaBienThe");

                    b.HasIndex("MaNguoiDung", "MaBienThe")
                        .IsUnique();

                    b.ToTable("GioHangs", t =>
                        {
                            t.HasCheckConstraint("CK_GioHang_SoLuong", "[SoLuong] > 0");
                        });
                });

            modelBuilder.Entity("backend.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HinhAnhSanPhams", t =>
                        {
                            t.HasCheckConstraint("CK_HinhAnhSanPham_ThuTu", "[ThuTu] >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("PhuongThucThanhToan")
                        .HasColumnType("tinyint");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("SoTienGiam")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TamTinh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("TrangThaiDonHang")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TrangThaiThanhToan")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HoaDons", t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_PhiVanChuyen", "[PhiVanChuyen] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_PhuongThucThanhToan", "[PhuongThucThanhToan] IN (0,1)");

                            t.HasCheckConstraint("CK_HoaDon_SoTienGiam", "[SoTienGiam] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TamTinh", "[TamTinh] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TongTien", "[TongTien] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TrangThaiDonHang", "[TrangThaiDonHang] IN (0,1,2,3)");

                            t.HasCheckConstraint("CK_HoaDon_TrangThaiThanhToan", "[TrangThaiThanhToan] IN (0,1)");
                        });
                });

            modelBuilder.Entity("backend.Models.KhuyenMai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaTriDonToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiamToiDa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhanTramGiam")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("KhuyenMais", t =>
                        {
                            t.HasCheckConstraint("CK_KhuyenMai_GiaTriDonToiThieu", "[GiaTriDonToiThieu] >= 0");

                            t.HasCheckConstraint("CK_KhuyenMai_GiamToiDa", "[GiamToiDa] >= 0");

                            t.HasCheckConstraint("CK_KhuyenMai_PhanTramGiam", "[PhanTramGiam] > 0 AND [PhanTramGiam] <= 100");

                            t.HasCheckConstraint("CK_KhuyenMai_SoLuong", "[SoLuong] >= 0");

                            t.HasCheckConstraint("CK_KhuyenMai_ThoiGian", "[NgayBatDau] < [NgayKetThuc]");
                        });
                });

            modelBuilder.Entity("backend.Models.MauSac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaHex")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenMau")
                        .IsUnique();

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("backend.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaQuyen");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs", t =>
                        {
                            t.HasCheckConstraint("CK_NguoiDung_TrangThai", "[TrangThai] IN (0,1)");
                        });
                });

            modelBuilder.Entity("backend.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenQuyen")
                        .IsUnique();

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("backend.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("SanPhams", t =>
                        {
                            t.HasCheckConstraint("CK_SanPham_GiaBan", "[GiaBan] >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenSize")
                        .IsUnique();

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("backend.Models.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenThuongHieu")
                        .IsUnique();

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("backend.Models.BienTheSanPham", b =>
                {
                    b.HasOne("backend.Models.MauSac", "MauSac")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.SanPham", "SanPham")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Size", "Size")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("MaSize")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("backend.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("backend.Models.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaBienThe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("backend.Models.DanhGia", b =>
                {
                    b.HasOne("backend.Models.ChiTietHoaDon", "ChiTietHoaDon")
                        .WithOne("DanhGia")
                        .HasForeignKey("backend.Models.DanhGia", "MaChiTietHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("backend.Models.GioHang", b =>
                {
                    b.HasOne("backend.Models.BienTheSanPham", "BienTheSanPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaBienThe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("backend.Models.SanPham", "SanPham")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("backend.Models.HoaDon", b =>
                {
                    b.HasOne("backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.NguoiDung", "NguoiDung")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("backend.Models.NguoiDung", b =>
                {
                    b.HasOne("backend.Models.PhanQuyen", "PhanQuyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("backend.Models.SanPham", b =>
                {
                    b.HasOne("backend.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("backend.Models.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("backend.Models.ChiTietHoaDon", b =>
                {
                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("backend.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("backend.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("backend.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("backend.Models.MauSac", b =>
                {
                    b.Navigation("BienTheSanPhams");
                });

            modelBuilder.Entity("backend.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("backend.Models.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("backend.Models.SanPham", b =>
                {
                    b.Navigation("BienTheSanPhams");

                    b.Navigation("DanhGias");

                    b.Navigation("HinhAnhSanPhams");
                });

            modelBuilder.Entity("backend.Models.Size", b =>
                {
                    b.Navigation("BienTheSanPhams");
                });

            modelBuilder.Entity("backend.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
